// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(ComputerStoreContext))]
    [Migration("20211230225701_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Computer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ComputerPrice")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("Models.Content", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ComputerID")
                        .HasColumnType("int");

                    b.Property<int?>("HardwareID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ComputerID");

                    b.HasIndex("HardwareID");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Models.Hardware", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("HardwareInfo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("HardwareName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HardwarePrice")
                        .HasColumnType("int");

                    b.Property<int>("TipID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("Models.Shelf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ComputerID")
                        .HasColumnType("int");

                    b.Property<int?>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ComputerID");

                    b.HasIndex("StoreID");

                    b.ToTable("Shelfs");
                });

            modelBuilder.Entity("Models.Store", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ShelfSize")
                        .HasColumnType("int");

                    b.Property<string>("StoreAddress")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Models.Tip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ComponenaTip")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Models.Content", b =>
                {
                    b.HasOne("Models.Computer", "Computer")
                        .WithMany("ComputerHardware")
                        .HasForeignKey("ComputerID");

                    b.HasOne("Models.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareID");

                    b.Navigation("Computer");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Models.Shelf", b =>
                {
                    b.HasOne("Models.Computer", "Computer")
                        .WithMany("ComputerStore")
                        .HasForeignKey("ComputerID");

                    b.HasOne("Models.Store", "Store")
                        .WithMany("StoreComputer")
                        .HasForeignKey("StoreID");

                    b.Navigation("Computer");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Models.Computer", b =>
                {
                    b.Navigation("ComputerHardware");

                    b.Navigation("ComputerStore");
                });

            modelBuilder.Entity("Models.Store", b =>
                {
                    b.Navigation("StoreComputer");
                });
#pragma warning restore 612, 618
        }
    }
}
